{
 "title": "Telegram Bot Logs",
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "file",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "INFO в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"$file\"} |= \"INFO\" [$__auto]))"
    }
   ]
  },
  {
   "title": "Предупреждения в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"$file\"} |= \"WARNING\" [$__auto]))"
    }
   ]
  },
  {
   "title": "Ошибки в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"$file\"} |= \"ERROR\" [$__auto]))"
    }
   ]
  },
  {
   "title": "Количество логов в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"$file\"} [$__auto]))"
    }
   ]
  }
 ]
}