clients:
  - url: http://loki-local:3100/loki/api/v1/push
    tenant_id: fake

scrape_configs:
  - job_name: telegram-bot
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /logs/bot.log
